### ISSUE TITLE
Security Issues on Source Code

### ISSUE THREAD

**Issue by asyncfinkd** [hasanharman/form-builder#2]
Hi, while parsing the code I found that Google Analytics (GA) Ids are open even with Google Tag Manager ID (gtmId). It would be better if this is exported in a separate .env. As you have other environments.

ex: NEXT_PUBLIC_POSTHOG_KEY, NEXT_OPEN_PANEL_CLIENT_ID, etc.

It would be better if these Keys were not NEXT_PUBLIC, it violates the security part...

--- 

From ChatGPT when i'm asking why we won't use NEXT_PUBLIC for sensitive environment's

Variables prefixed with NEXT_PUBLIC are exposed to the client-side, making them accessible in the browser’s developer tools. This can be a security risk if you are handling sensitive data such as API keys, tokens, or database credentials. Any sensitive or private information should remain server-side and not be exposed to the client.

---

More on this topic: https://stackoverflow.com/a/70766460

**Comment by hasanharman** [comment]
Thank you for the great recommendations. I'd like to connect with you let's talk on [twitter](https://x.com/strad3r)
