### ISSUE TITLE
Datetime component overflows in side by side render

### ISSUE THREAD

**Issue by dragonfleas** [hasanharman/form-builder#21]
# Description
If you select the `Datetime Picker` component, in side-by-side mode with another component, there is overflow occurring on the right side of the component. Screenshot below shows behavior.

I was able to replicate this on both Firefox & Chromium browsers.

![image](https://github.com/user-attachments/assets/e832cfdc-3cfa-4f06-bf3f-6771ec5b035d)
![image](https://github.com/user-attachments/assets/f76b53d0-cdfe-4688-9e20-a0b9d94f33ac)

**Comment by hasanharman** [comment]
Thank you for informing, will be fixed this week

**Comment by hasanharman** [comment]
It is fixed, thank you for reporting 🙌
