### ISSUE TITLE
Smart Datetime Input component sometimes fails validation

### ISSUE THREAD

**Issue by phxgg** [hasanharman/form-builder#22]
In the `Smart Datetime Input` component, almost every time I type anything in the input box, it is going to fail validation unless I press Enter (or click Submit), then add a whitespace in the input and re-submit the form.

https://github.com/user-attachments/assets/c987df05-4bcf-457a-954e-041968bfcd72

**Comment by hasanharman** [comment]
It is fixed, thank you for reporting 🙌
