### ISSUE TITLE
Resizing issue when deleting adjacent components

### ISSUE THREAD

**Issue by Niketh1234** [hasanharman/form-builder#23]
The component is not taking the entire width if another adjacent component is deleted instead it is having the same width and malfunctioning while changing the order of the components. Please check the below screenshots for reference.

![Screenshot 2024-11-06 104144](https://github.com/user-attachments/assets/4fdef253-d05f-497c-b3db-79073a0c37d7)
![Screenshot 2024-11-06 104232](https://github.com/user-attachments/assets/3772aa89-42ba-4bbe-8104-cbd62b20ab8a)

**Comment by hasanharman** [comment]
Nice catch! Will fix that in next update. I will add adding custom classNames soon.

**Comment by hasanharman** [comment]
It is fixed, thank you for reporting 🙌
