### ISSUE TITLE
Signature Input does not clear last position of drawing

### ISSUE THREAD

**Issue by phxgg** [hasanharman/form-builder#29]
As shown in **clip 1**, the Signature Input does not clear the last position of the drawing when pressing the Clear button.

Also, not sure if this is supposed to work this way, but if you click to start drawing more than once in the canvas, your latest click will connect with a straight line to the last position if the previous click. See **clip 2**

https://github.com/user-attachments/assets/192248e6-a60a-453f-a540-03c7c7d110ed

https://github.com/user-attachments/assets/2efdef3c-305b-4f8b-ac22-e50b1d548ae7

**Comment by hasanharman** [comment]
Thank you for noticing the issue, will be fixed this week
